apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: component-ob2gg66fvivzm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: component-ob2gg66fvivzm
    app.kubernetes.io/part-of: test-gitlabrenovate-i2dz0321wt5za
  name: component-ob2gg66fvivzm
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: component-ob2gg66fvivzm
status:
  loadBalancer: {}
